### ISSUE TITLE
context creation backwards compatibility

### ISSUE THREAD

**Issue by kafonek** [nbgallery/pypki2#22]
Please leave a convenience function in newer versions of pypki2 that maintains backwards compatibility for creating a new context, to give other libraries an opportunity to adopt the new syntax without breaking due to version mismatches.

The legacy code is - 
```python
import pypki2
pypki = pypki2._pypki_loader
context = pypki2.new_context
```

The new version of that code is
```python
import pypki2config
context = pypki2config.ssl_context()
```

**Comment by billallen256** [comment]
Released as 0.10.2.  16f818970a69bce27c9e1bfdf293ebb447cf5943
