### ISSUE TITLE
PermissionIssue in pypki2pip

### ISSUE THREAD

**Issue by lantzmw** [nbgallery/pypki2#24]
A permission error is thrown when trying to use pypki2pip. The PermissionError is thrown because pip.main is unable to use the open NamedTemporaryFile. If the file is closed, pip.main can access the cert file and use it to connect.

I put in a pull request with an example that works for me, but is admittedly not tested robustly. The pip_pki_exec function may need to reflect the same changes, but I'm not sure how that would work when returning the `executor_returned` variable

**Comment by billallen256** [comment]
This looks related to #4, and may actually point to a new issue in `pip_pki_exec` as well.  I'll investigate.

It's also worth pointing out that `pip.main()` (referenced in #23) does not work with pip 10, which was the main reason for all the recent changes in the ipydeps package, and the creation of `pip_pki_exec()` in pypki2.

**Comment by billallen256** [comment]
This should be addressed at this point, as pypki3 now calls pip as a separate process like ipydeps.
