### ISSUE TITLE
Create CI integration for Windows and Travis CI

### ISSUE THREAD

**Issue by linwoodc3** [nbgallery/pypki2#25]
We can easily test our install and unittests with GitHub's CI integration for Windows and Linux-based systems.  

That just requires us creating a travis.yml file for the Linux/MacOS and an appveyor test for the Windows CI testing.  I have some expericence with this on my project so will make the file. 

https://travis-ci.org/linwoodc3/gdeltPyR

**Comment by billallen256** [comment]
@somedave I looked at Travis CI briefly for ipydeps, and I think it requires limited access permissions from the nbgallery organization as a whole.  Do you see any issues with that?

**Comment by billallen256** [comment]
pypki3 uses GitHub workflows for CI.
