### ISSUE TITLE
pypki2pip may be incompatible with pip 19.3.1

### ISSUE THREAD

**Issue by sethfaulkner** [nbgallery/pypki2#27]
Hello,
I am hoping to use this tool with pkis. Running pypki2pip.pip([*args*]) produces the error 'module pip has no attribute 'main'' I believe this is due to a recent pip reformat.

I was able to fix the issue for me by replacing 
```python
import pip as _pip
```
with
```python
from pip._internal import main as _pip
```

This doesn't seem good for backwards compatibility. Is this packages still managed?

**Comment by billallen256** [comment]
Take a look at the ipydeps package, which integrates with pypki2 to enable pip with PKI. I should probably remove pypki2.pip() as it has been supplanted by ipydeps.pip().
