### ISSUE TITLE
P12Loader().new_context() - Errors in Windows Environment

### ISSUE THREAD

**Issue by ctaylor08** [nbgallery/pypki2#4]
Using an Anaconda distribution on Windows with recommended environment variables, receiving Permission Error [Errno 13] due to new_context() function in class _P12Loader(). The traceback pointed to the NamedTemporaryFile object. From the docs:

*Whether the name can be used to open the file a second time, while the named temporary file is still open, varies across platforms (it can be so used on Unix; it **cannot on Window NT or later**).*

So, I rewrote the new_context function, doing away with the with loop, and it seems to work fine now. Hopefully this is a viable solution, but at the very least, it is a push in the right direction.

The old function:
```python
def new_context(self, protocol=ssl.PROTOCOL_SSLv23):
    p12 = self._load(self.filename, self.password)
    c = ssl.SSLContext(protocol)
    with NamedTemporaryFile() as f:
        _write_pem_with_password(p12, f, self.password)
        c.load_cert_chain(f.name, password=self.password)
    return c
```

The new function:
```python
def new_context(self, protocol=ssl.PROTOCOL_SSLv23):
    p12 = self._load(self.filename, self.password)
    c = ssl.SSLContext(protocol)
    f = NamedTemporaryFile(delete=False)
    _write_pem_with_password(p12, f, self.password)
    f.close()
    c.load_cert_chain(f.name, password=self.password)
    os.unlink(f.name)
    return c
```

**Comment by billallen256** [comment]
Thanks for the fix.  Added in 30ae85027ef58879eb9788e9635e9f6b8745dd5e.
