### ISSUE TITLE
Windows - replace MYPKI_CONFIG env variable with USERPROFILE

### ISSUE THREAD

**Issue by ctaylor08** [nbgallery/pypki2#5]
If I had git set up on this machine, I'd submit a Pull request, but I don't.

I was setting up a friend with pypki2 - he is using a Windows 7 machine with Anaconda installed- and when we tried using it the first time, this PyPKI2Exception raised:

'Could not find MYPKI_CONFIG or HOME environment variables.  If you are on Windows, you need to add a MYPKI_CONFIG environment variable in Control Panel.  See Windows Configuration in README.md for further instructions.'

It's easy enough to do, but I thought I'd try to get pypki2 working without any pre-configuration needed.

My first crack at a solution was to get the USERPROFILE environment, instead of creating a new MYPKI_CONFIG variable. I got rid of the mypki_config_path() and home_config_path() functions, and rewrote the get_config_path() function to:
```python
def get_config_path():
    # home location on LINUX/UNIX == 'HOME', on WINDOWS == 'USERPROFILE'
    p = os.environ.get('HOME') or os.environ.get('USERPROFILE')
    if p is not None and os.path.exists(p):
        return p
    raise PyPKI2Exception('Could not find a user-specific profile on this machine')
```

That seems to work, though it's dependent on the existence of the 'USERPROFILE' variable on Windows. My research seems to indicate that it will exist on all Windows operating systems, but just in case, the PyPKI2Exception's message could be tweaked.

**Comment by billallen256** [comment]
I'm going to try os.path.expanduser("~") the next time I'm on a Windows box.  Per http://stackoverflow.com/questions/4028904/how-to-get-the-home-directory-in-python

**Comment by billallen256** [comment]
pypki3 now uses pathlib.Path.home().
