### ISSUE TITLE
Add support for passwordless certs

### ISSUE THREAD

**Issue by billallen256** [nbgallery/pypki2#6]
There are some non-interactive use-cases for some of the packages that use pypki2, where the user is legitimately using an unencrypted cert.

**Comment by messiaen** [comment]
Created a [pull request](https://github.com/nbgallery/pypki2/pull/8) for this.

**Comment by billallen256** [comment]
Fixed in release 0.8.0: https://github.com/nbgallery/pypki2/commit/8cff4cc5998955ed4cad0926bf68e55c1bca288b

https://pypi.org/project/pypki2/0.8.0/
